<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXecshZB\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXecshZB/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXecshZB.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXecshZB\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXecshZB\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XecshZB',
    'container.build_id' => '0371f1d8',
    'container.build_time' => 1541520196,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXecshZB');
